/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.QuanLy;

import Models.NgheNghiep;
import Models.NgheNghiepSoThich;
import Models.SoThich;
import Mysql.ConnectSQL;
import Mysql.NgheNghiepSoThichDAO;
import Mysql.SearchSanPhamDAO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class DLQl_Sua_So_Thich_Nghe_Nghiep extends javax.swing.JDialog {

    ConnectSQL cn = new ConnectSQL();
    NgheNghiepSoThichDAO ngheNghiepSoThichDAO = new NgheNghiepSoThichDAO(cn.getCn());
    SearchSanPhamDAO searchSanPhamDAO = new SearchSanPhamDAO(cn.getCn());

    /**
     * Creates new form DLQl_Sua_So_Thich
     *
     * @param parent
     * @param modal
     */
    String MaSoThichNN;

    public DLQl_Sua_So_Thich_Nghe_Nghiep(java.awt.Frame parent, boolean modal, String masothich) {
        super(parent, modal);
        initComponents();
        NgheNghiepSoThich l = ngheNghiepSoThichDAO.getNgheNghiepSoThich(masothich);

        showAllSoThich();
        showAllNgheNghiep();
        MaSoThichNN = masothich;
        SoThich soThich = cn.GetSoThichByMa(l.getId_sothich() + "");
        jcbSoThich.setSelectedItem(soThich.GetTenSoThich());
        NgheNghiep ngheNghiep = cn.GetNgheNghiepByMa(l.getId_nghenghiep() + "");
        jcbNgheNghiep.setSelectedItem(ngheNghiep.GetTenNgheNghiep());
    }

    public void showAllNgheNghiep() {
        // Tạo mô hình cho JComboBox
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        List<NgheNghiep> khoangGias = searchSanPhamDAO.getAllNgheNghiep();
        // Thêm các giá trị vào mô hình
        for (NgheNghiep gia : khoangGias) {
            model.addElement(gia.GetTenNgheNghiep());
        }

        // Gán mô hình cho JComboBox
        jcbNgheNghiep.setModel(model);
    }

    public void showAllSoThich() {
        // Tạo mô hình cho JComboBox
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        List<SoThich> khoangGias = searchSanPhamDAO.getAllSoThich();
        // Thêm các giá trị vào mô hình
        for (SoThich gia : khoangGias) {
            model.addElement(gia.GetTenSoThich());
        }
        // Gán mô hình cho JComboBox
        jcbSoThich.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblten = new javax.swing.JLabel();
        btnHuyBo = new javax.swing.JButton();
        btnXacNhan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jcbNgheNghiep = new javax.swing.JComboBox<>();
        jcbSoThich = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblten.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblten.setForeground(new java.awt.Color(51, 0, 51));
        lblten.setText("Sửa sở thích - nghề nghiệp");

        btnHuyBo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnHuyBo.setForeground(new java.awt.Color(51, 0, 51));
        btnHuyBo.setText("Hủy bỏ");
        btnHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBoActionPerformed(evt);
            }
        });

        btnXacNhan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(51, 0, 51));
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nghề nghiệp");

        jcbNgheNghiep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcbSoThich.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Sở thích");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbNgheNghiep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbSoThich, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(btnXacNhan)
                                .addGap(18, 18, 18)
                                .addComponent(btnHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(lblten)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblten)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbSoThich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbNgheNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBoActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyBoActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        String tenNgheNghiep = (String) jcbNgheNghiep.getSelectedItem();
        String tenSoThich = (String) jcbSoThich.getSelectedItem();

        SoThich soThich = cn.GetSoThichByTen(tenSoThich);
        NgheNghiep ngheNghiep = cn.GetNgheNghiepByTen(tenNgheNghiep);
        SoThich sothich = new SoThich();
        ngheNghiepSoThichDAO.updateNgheNghiepSoThich(Integer.parseInt(MaSoThichNN), Integer.parseInt(ngheNghiep.GetMaNgheNghiep()), Integer.parseInt(soThich.GetMaSoThich()));
        Jp_QLSoThich_NgheNghiep.sothich_nghenghiep.FillTable();
        Jp_QLSoThich_NgheNghiep.sothich_nghenghiep.updateUI();
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnXacNhanActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyBo;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcbNgheNghiep;
    private javax.swing.JComboBox<String> jcbSoThich;
    private javax.swing.JLabel lblten;
    // End of variables declaration//GEN-END:variables
}
