/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.QuanLy;

/**
 *
 * @author LONG
 */
public class JpQuanLy extends javax.swing.JPanel {

    /**
     * Creates new form JpQuanLy
     */
    public JpQuanLy() {
        initComponents();
        LoadPanel(1);
    }
    Jp_QLSanPham sp;
    Jp_QLHangSanXuat hsx;
    Jp_QLTaiKhoan tk;
    Jp_QLTinhNang tn;
    Jp_QLMauSac ms;
    Jp_QLKieuDang kd;
    Jp_QLKhoangGia kg;
    Jp_QLNgheNghiep nn;
    Jp_QLSoThich st;
    Jp_QLSoThich_NgheNghiep qLSoThich_NgheNghiep;

    public void LoadPanel(int i) {
        jpql.removeAll();
        switch (i) {
            case 1:
                if (sp == null) {
                    sp = new Jp_QLSanPham();
                }
                jpql.add(sp);
                break;
            case 2:
                if (hsx == null) {
                    hsx = new Jp_QLHangSanXuat();
                }
                jpql.add(hsx);
                break;
            case 3:
                if (tk == null) {
                    tk = new Jp_QLTaiKhoan();
                }
                jpql.add(tk);
                break;
            case 4:
                if (tn == null) {
                    tn = new Jp_QLTinhNang();
                }
                jpql.add(tn);
                break;
            case 5:
                if (ms == null) {
                    ms = new Jp_QLMauSac();
                }
                jpql.add(ms);
                break;
            case 6:
                if (kd == null) {
                    kd = new Jp_QLKieuDang();
                }
                jpql.add(kd);
                break;
            case 7:
                if (kg == null) {
                    kg = new Jp_QLKhoangGia();
                }
                jpql.add(kg);
                break;
            case 8:
                if (nn == null) {
                    nn = new Jp_QLNgheNghiep();
                }
                jpql.add(nn);
                break;
            case 9:
                if (st == null) {
                    st = new Jp_QLSoThich();
                }
                jpql.add(st);
                break;
            case 10:
                if (qLSoThich_NgheNghiep == null) {
                    qLSoThich_NgheNghiep = new Jp_QLSoThich_NgheNghiep();
                }
                jpql.add(qLSoThich_NgheNghiep);
                break;
            default:
                break;

        }
        jpql.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnQLHSX = new javax.swing.JButton();
        btnQLTN = new javax.swing.JButton();
        btnQLTK = new javax.swing.JButton();
        btnQLMS = new javax.swing.JButton();
        btnQLKD = new javax.swing.JButton();
        btnQLSP = new javax.swing.JButton();
        btnQLNN = new javax.swing.JButton();
        btnQLST = new javax.swing.JButton();
        btnQLKG = new javax.swing.JButton();
        btnQLST2 = new javax.swing.JButton();
        jpql = new javax.swing.JPanel();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(1051, 486));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnQLHSX.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnQLHSX.setForeground(new java.awt.Color(51, 51, 0));
        btnQLHSX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/kiemke.png"))); // NOI18N
        btnQLHSX.setText("QUẢN LÝ HÃNG SẢN XUẤT");
        btnQLHSX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLHSX.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnQLHSX.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQLHSX.setIconTextGap(10);
        btnQLHSX.setPreferredSize(new java.awt.Dimension(0, 35));
        btnQLHSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLHSXActionPerformed(evt);
            }
        });

        btnQLTN.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnQLTN.setForeground(new java.awt.Color(51, 51, 0));
        btnQLTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icontinhnang.jpg"))); // NOI18N
        btnQLTN.setText("QUẢN LÝ TÍNH NĂNG");
        btnQLTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLTN.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnQLTN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQLTN.setIconTextGap(10);
        btnQLTN.setPreferredSize(new java.awt.Dimension(0, 35));
        btnQLTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTNActionPerformed(evt);
            }
        });

        btnQLTK.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnQLTK.setForeground(new java.awt.Color(51, 51, 0));
        btnQLTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/qluser.png"))); // NOI18N
        btnQLTK.setText("QUẢN LÝ TÀI KHOẢN");
        btnQLTK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLTK.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnQLTK.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQLTK.setIconTextGap(10);
        btnQLTK.setPreferredSize(new java.awt.Dimension(0, 35));
        btnQLTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTKActionPerformed(evt);
            }
        });

        btnQLMS.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnQLMS.setForeground(new java.awt.Color(51, 51, 0));
        btnQLMS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/iconmausac.png"))); // NOI18N
        btnQLMS.setText("QUẢN LÝ MÀU SẮC");
        btnQLMS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLMS.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnQLMS.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQLMS.setIconTextGap(10);
        btnQLMS.setPreferredSize(new java.awt.Dimension(0, 35));
        btnQLMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLMSActionPerformed(evt);
            }
        });

        btnQLKD.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnQLKD.setForeground(new java.awt.Color(51, 51, 0));
        btnQLKD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/iconkieudang.png"))); // NOI18N
        btnQLKD.setText("QUẢN LÝ KIỂU DÁNG");
        btnQLKD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLKD.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnQLKD.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQLKD.setIconTextGap(10);
        btnQLKD.setPreferredSize(new java.awt.Dimension(0, 35));
        btnQLKD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLKDActionPerformed(evt);
            }
        });

        btnQLSP.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnQLSP.setForeground(new java.awt.Color(51, 51, 0));
        btnQLSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/mailinglist.jpg"))); // NOI18N
        btnQLSP.setText("QUẢN LÝ SẢN PHẨM");
        btnQLSP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLSP.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnQLSP.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQLSP.setIconTextGap(10);
        btnQLSP.setPreferredSize(new java.awt.Dimension(0, 35));
        btnQLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSPActionPerformed(evt);
            }
        });

        btnQLNN.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnQLNN.setForeground(new java.awt.Color(51, 51, 0));
        btnQLNN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/iconnghenghiep.png"))); // NOI18N
        btnQLNN.setText("QUẢN LÝ NGHỀ NGHIỆP");
        btnQLNN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLNN.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnQLNN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQLNN.setIconTextGap(10);
        btnQLNN.setPreferredSize(new java.awt.Dimension(0, 35));
        btnQLNN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNNActionPerformed(evt);
            }
        });

        btnQLST.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnQLST.setForeground(new java.awt.Color(51, 51, 0));
        btnQLST.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/iconsothich.png"))); // NOI18N
        btnQLST.setText("QUẢN LÝ SỞ THÍCH");
        btnQLST.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLST.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnQLST.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQLST.setIconTextGap(10);
        btnQLST.setPreferredSize(new java.awt.Dimension(0, 35));
        btnQLST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSTActionPerformed(evt);
            }
        });

        btnQLKG.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnQLKG.setForeground(new java.awt.Color(51, 51, 0));
        btnQLKG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/iconkhoanggia.png"))); // NOI18N
        btnQLKG.setText("QUẢN LÝ KHOẢNG GIÁ");
        btnQLKG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLKG.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnQLKG.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQLKG.setIconTextGap(10);
        btnQLKG.setPreferredSize(new java.awt.Dimension(0, 35));
        btnQLKG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLKGActionPerformed(evt);
            }
        });

        btnQLST2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnQLST2.setForeground(new java.awt.Color(51, 51, 0));
        btnQLST2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/iconsothich.png"))); // NOI18N
        btnQLST2.setText("SỞ THÍCH - NGHỀ NGHIỆP");
        btnQLST2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLST2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnQLST2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQLST2.setIconTextGap(10);
        btnQLST2.setPreferredSize(new java.awt.Dimension(0, 35));
        btnQLST2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLST2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnQLST, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(btnQLNN, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(btnQLKG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQLKD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQLMS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQLTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQLTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQLHSX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQLSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnQLST2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQLSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnQLHSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQLTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnQLTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQLMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQLKD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQLKG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQLNN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQLST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQLST2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpql.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpql, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpql, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1123, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTNActionPerformed
        LoadPanel(4);// TODO add your handling code here:
    }//GEN-LAST:event_btnQLTNActionPerformed

    private void btnQLHSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLHSXActionPerformed
        LoadPanel(2);// TODO add your handling code here:
    }//GEN-LAST:event_btnQLHSXActionPerformed

    private void btnQLTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTKActionPerformed
        LoadPanel(3);  // TODO add your handling code here:
    }//GEN-LAST:event_btnQLTKActionPerformed

    private void btnQLMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLMSActionPerformed
        LoadPanel(5);// TODO add your handling code here:
    }//GEN-LAST:event_btnQLMSActionPerformed

    private void btnQLKDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLKDActionPerformed
        LoadPanel(6);// TODO add your handling code here:
    }//GEN-LAST:event_btnQLKDActionPerformed

    private void btnQLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSPActionPerformed
        LoadPanel(1);// TODO add your handling code here:
    }//GEN-LAST:event_btnQLSPActionPerformed

    private void btnQLNNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNNActionPerformed
        LoadPanel(8);// TODO add your handling code here:
    }//GEN-LAST:event_btnQLNNActionPerformed

    private void btnQLSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSTActionPerformed
        LoadPanel(9);// TODO add your handling code here:
    }//GEN-LAST:event_btnQLSTActionPerformed

    private void btnQLKGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLKGActionPerformed
        LoadPanel(7);// TODO add your handling code here:
    }//GEN-LAST:event_btnQLKGActionPerformed

    private void btnQLST2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLST2ActionPerformed
LoadPanel(10);    }//GEN-LAST:event_btnQLST2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQLHSX;
    private javax.swing.JButton btnQLKD;
    private javax.swing.JButton btnQLKG;
    private javax.swing.JButton btnQLMS;
    private javax.swing.JButton btnQLNN;
    private javax.swing.JButton btnQLSP;
    private javax.swing.JButton btnQLST;
    private javax.swing.JButton btnQLST2;
    private javax.swing.JButton btnQLTK;
    private javax.swing.JButton btnQLTN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jpql;
    // End of variables declaration//GEN-END:variables
}
