/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface.BanHang;

import Models.KhoangGia;
import Models.KieuDang;
import Models.MauSac;
import Models.NgheNghiep;
import Models.SanPham;
import Models.SoThich;
import Models.TinhNang;
import Mysql.ConnectSQL;
import Mysql.SearchSanPhamDAO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class JpTuVan extends javax.swing.JPanel {
    ConnectSQL connectSQL = new ConnectSQL();
    SearchSanPhamDAO searchSanPhamDAO = new SearchSanPhamDAO(connectSQL.getCn());

    /**
     * Creates new form JpTuVan
     */
    public JpTuVan() {
        initComponents();
        showKhoangGia();
        showAllKieuDang();
        showAllMauSac();
        showAllNgheNghiep();
        showAllSoThich();
        showAllTinhNang();
        
    }
    
    public void showKhoangGia(){
        // Tạo mô hình cho JComboBox
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement(null);
        List<KhoangGia> khoangGias = searchSanPhamDAO.getAllKhoangGia();
        // Thêm các giá trị vào mô hình
        for (KhoangGia gia : khoangGias) {
             model.addElement(gia.GetTenKhoangGia());
        }    

        // Gán mô hình cho JComboBox
        jcbKhoangGia.setModel(model);
    }
    
    public void showAllTinhNang(){
        // Tạo mô hình cho JComboBox
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement(null);
        List<TinhNang> khoangGias = searchSanPhamDAO.getAllTinhNang();
        // Thêm các giá trị vào mô hình
        for (TinhNang gia : khoangGias) {
             model.addElement(gia.GetTenTinhNang());
        }    

        // Gán mô hình cho JComboBox
        jcbTinhNang.setModel(model);
    }

    
    public void showAllKieuDang(){
        // Tạo mô hình cho JComboBox
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement(null);

        List<KieuDang> khoangGias = searchSanPhamDAO.getAllKieuDang();
        // Thêm các giá trị vào mô hình
        for (KieuDang gia : khoangGias) {
             model.addElement(gia.GetTenKieuDang());
        }    

        // Gán mô hình cho JComboBox
        jcbKieuDang.setModel(model);
    }
    
     public void showAllMauSac(){
        // Tạo mô hình cho JComboBox
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement(null);
        List<MauSac> khoangGias = searchSanPhamDAO.getAllMauSac();
        // Thêm các giá trị vào mô hình
        for (MauSac gia : khoangGias) {
             model.addElement(gia.GetTenMauSac());
        }    

        // Gán mô hình cho JComboBox
        jcbMauSac.setModel(model);
    }
     
     public void showAllNgheNghiep(){
        // Tạo mô hình cho JComboBox
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement(null);
        List<NgheNghiep> khoangGias = searchSanPhamDAO.getAllNgheNghiep();
        // Thêm các giá trị vào mô hình
        for (NgheNghiep gia : khoangGias) {
             model.addElement(gia.GetTenNgheNghiep());
        }    

        // Gán mô hình cho JComboBox
        jcbNgheNghiep.setModel(model);
    }
     
     public void showAllSoThich(){
        // Tạo mô hình cho JComboBox
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement(null);

        List<SoThich> khoangGias = searchSanPhamDAO.getAllSoThich();
        // Thêm các giá trị vào mô hình
        for (SoThich gia : khoangGias) {
             model.addElement(gia.GetTenSoThich());
        }    
        // Gán mô hình cho JComboBox
        jcbSoThich.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfHoTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jrbNam = new javax.swing.JRadioButton();
        jrbNu = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jcbNgheNghiep = new javax.swing.JComboBox<>();
        jcbSoThich = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jcbKhoangGia = new javax.swing.JComboBox<>();
        jcbKieuDang = new javax.swing.JComboBox<>();
        jcbTinhNang = new javax.swing.JComboBox<>();
        jcbMauSac = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("HỆ TƯ VẤN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Họ tên");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Sở thích");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nghề nghiệp");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Giới tính");

        jrbNam.setText("Nam");

        jrbNu.setText("Nữ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "MaSP", "TenSP", "GiaSP"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jcbNgheNghiep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcbSoThich.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Khoảng giá");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Kiểu dáng");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Tính năng");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Màu sắc");

        jcbKhoangGia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcbKieuDang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcbTinhNang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcbMauSac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Tư vấn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jcbKieuDang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbKhoangGia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel5))
                            .addComponent(jcbSoThich, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jrbNam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbNu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbMauSac, 0, 148, Short.MAX_VALUE)
                            .addComponent(jcbTinhNang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jcbNgheNghiep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(505, 505, 505)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jrbNam)
                            .addComponent(jrbNu))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jcbNgheNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbSoThich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(jcbKhoangGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbTinhNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jcbKieuDang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("MaSanPham");
        tableModel.addColumn("TenSanPham");
        tableModel.addColumn("GiaSanPham");


        String tenKhoangGia = (String) jcbKhoangGia.getSelectedItem();
        String tenKieuDang = (String) jcbKieuDang.getSelectedItem();
        String tenMauSac = (String) jcbMauSac.getSelectedItem();
        String tenNgheNghiep = (String) jcbNgheNghiep.getSelectedItem();
        String tenSoThich= (String) jcbSoThich.getSelectedItem();
        String tenTinhNang = (String) jcbTinhNang.getSelectedItem();
        
         tenKhoangGia = tenKhoangGia == "" ? null: tenKhoangGia;
         tenKieuDang = tenKieuDang == "" ? null: tenKieuDang;
         tenMauSac = tenMauSac == "" ? null: tenMauSac;
         tenNgheNghiep = tenNgheNghiep == "" ? null: tenNgheNghiep;
         tenSoThich= tenSoThich == "" ? null: tenSoThich;
         tenTinhNang =tenTinhNang == "" ? null: tenTinhNang;
         System.out.println("---------------------");
         System.out.println("tenKhoangGia");
         System.out.println(tenKhoangGia);
          System.out.println("tenNgheNghiep");
         System.out.println(tenNgheNghiep);


        List<Integer> idst_nn = searchSanPhamDAO.searchNgheNghiepSoThich(tenNgheNghiep, tenSoThich);
        List<SanPham> sanPhams = searchSanPhamDAO.searchSanPham(tenKieuDang, tenMauSac, tenTinhNang, tenKhoangGia, idst_nn );
        System.out.println("sp");
        System.out.println(sanPhams.size());

        for (SanPham sanPham : sanPhams) {
            Object[] rowData = {sanPham.GetMaSanPham(), sanPham.GetTenSanPham(), sanPham.GetDonGia()};
            tableModel.addRow(rowData);
        }
        
        jTable1.setModel(tableModel);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcbKhoangGia;
    private javax.swing.JComboBox<String> jcbKieuDang;
    private javax.swing.JComboBox<String> jcbMauSac;
    private javax.swing.JComboBox<String> jcbNgheNghiep;
    private javax.swing.JComboBox<String> jcbSoThich;
    private javax.swing.JComboBox<String> jcbTinhNang;
    private javax.swing.JRadioButton jrbNam;
    private javax.swing.JRadioButton jrbNu;
    private javax.swing.JTextField jtfHoTen;
    // End of variables declaration//GEN-END:variables
}
